import { renderOgImage, ogSize, ogAlt, ogContentType } from "@/lib/og";

// A real PNG social-share image, generated by next/og. (SVG og:images are not
// rendered by most social platforms — this fixes link previews.)
export const runtime = "edge";
export const alt = ogAlt;
export const size = ogSize;
export const contentType = ogContentType;

export default function Image() {
  return renderOgImage();
}
